import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [input, setInput] = useState({
    alias: "",
    topic: "",
  });

  const { mutate, data, isLoading } = api.youtube.youtube.useMutation();

  return (
    <>
      <Head>
        <title>Youtube video title generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <label>
            alias
            <input
              className="border border-slate-500"
              type="text"
              value={input.alias}
              placeholder="alias"
              onChange={(e) =>
                setInput((prev) => ({ ...prev, alias: e.target.value }))
              }
            />
          </label>
        </div>
        <div>
          <label>
            topic
            <input
              className="border border-slate-500"
              type="text"
              value={input.topic}
              placeholder="topic"
              onChange={(e) =>
                setInput((prev) => ({ ...prev, topic: e.target.value }))
              }
            />
          </label>
        </div>

        <button
          type="button"
          onClick={() => {
            mutate({ topic: input.topic, alias: `@${input.alias}` });
          }}
        >
          Go
        </button>

        {isLoading && <p>Loading...</p>}
        {data && <p>Your result: {data}</p>}
      </main>
    </>
  );
};

export default Home;
